### ISSUE TITLE
Map 4 Checklist

### ISSUE THREAD

**Issue by j-rockwell** [hcfrevival/factions#140]
- [ ] Map Pregen (see: https://github.com/pop4959/Chunky/wiki/Installing)
- [x] Claims (General)
- [x] Claims (Buffers)
- [x] Wand Subclaims
- [ ] Chest Subclaims
- [ ] Commands
- [ ] Crowbars
- [x] Leaderboards/Displays
- [ ] Events
- [x] Combat Loggers
- [x] Stats
- [ ] Deathbans
- [ ] Server States (SOTW, Normal and EOTW Modes)
- [x] Spawnpoints
- [ ] Lobby Queue

Command Tests:
- [ ] /f create
- [ ] /f createserver <name>
- [ ] /f invite <name>
- [ ] /f uninvite <name>
- [ ] /f join <name>
- [ ] /f leave
- [ ] /f disband
- [ ] /f rename
- [ ] /f sethome
- [ ] /f unsethome
- [ ] /f show
- [ ] /f list
- [ ] /f chat
- [ ] /f freeze
- [ ] /f thaw
- [ ] /f setdtr
- [ ] /f setflag
- [ ] /f setdisplay
- [ ] /f setbuffer
- [ ] /f setreinv
- [ ] /f map
- [ ] /f claim
- [ ] /f unclaim
- [ ] /f subclaim <name>
- [ ] /f subclaim <add|remove> <name>
- [ ] /f subclaims
- [ ] /f unsubclaim
- [ ] /f stuck
- [ ] /f home
- [ ] /f kick
- [ ] /f kick <name>
- [ ] /f announcement
- [ ] /f promote <name>
- [ ] /f demote <name>
- [ ] /f deposit
- [ ] /f withdraw
- [ ] /f token <add|remove> <name> <amount>
- [ ] /f rally
- [ ] /tl /fl
- [ ] /lives
- [ ] /lives give <name> <amount>
- [ ] /revive
- [ ] /revive <name>
- [ ] /pvp enable
- [ ] /logout
